### ISSUE TITLE
Weird spacing for number inputs

### ISSUE THREAD

**Issue by mscharfstein** [ny/maslow#221] opened 2020-07-30 17:54 UTC
There's a weird space on the left hand side of the input bar for number inputs. Looks weirder for the currency inputs since the $ is far from the entered number

![image](https://user-images.githubusercontent.com/29430896/88956967-2a86ce00-d26c-11ea-96ce-913b1b263fb7.png)

**Comment by kebrahim** [comment] 2020-07-30 18:30
duplicate of #217

**Closed by kebrahim** 2020-07-30 18:30 UTC
Labels: bug, duplicate
